# Generated by Django 2.2.4 on 2020-02-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('director', models.CharField(max_length=255)),
                ('screenwriter', models.CharField(max_length=255)),
                ('actors', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=255)),
                ('initial', models.CharField(max_length=255)),
                ('runtime', models.CharField(max_length=100)),
                ('playUrl', models.CharField(max_length=1000)),
                ('rate', models.CharField(max_length=255)),
                ('starPeople', models.CharField(max_length=255)),
                ('preShowUrl', models.CharField(max_length=255)),
                ('intro', models.CharField(max_length=2555)),
                ('icon', models.CharField(max_length=255)),
            ],
        ),
    ]
